db:
  host: localhost
  port: 3307
  user: root
  password: 123456
  dbname: campaign
  sslmode: disable

redis:
  address: localhost:6379
  password: ""
  db: 0

logging:
  level: info
  format: text
  outputs:
    - type: file
      level: debug
      filename: "20060102_debug.log"
      maxSize: 500
      maxBackups: 3
      maxAge: 28
      compress: true
    - type: file
      level: info
      filename: "20060102_info.log"
      maxSize: 500
      maxBackups: 3
      maxAge: 28
      compress: true
    - type: file
      level: warn
      filename: "20060102_warn.log"
      maxSize: 500
      maxBackups: 3
      maxAge: 28
      compress: true
    - type: file
      level: error
      filename: "20060102_error.log"
      maxSize: 500
      maxBackups: 3
      maxAge: 28
      compress: true
    - type: console
  
geth:
  wsAddress: "ws://localhost:8545"
  address: "https://localhost:8545"
  donationContract:
    address: "0xA03384C52E88b60cecc00EEF44f827caECe072b5"
    abiPath: "abi/donation.abi"
  nftContract:
    address: "0x812f60E4e7822A2439504f5806410244136BFbd2"
    abiPath: "abi/nft.abi"
  nft:
    private_key: "4d793e28b59cae1f0680ebeda1fc70f8019dbd19041c725c02be75f6261962d9"  # NFT合约部署者私钥
    chain_id: 11155111                    # 链ID(如Goerli=5)

