db:
  host: localhost
  port: 3307
  user: root
  password: 123456
  dbname: campaign
  sslmode: disable

redis:
  address: localhost:6379
  password: ""
  db: 0

logging:
  level: info
  format: text
  outputs:
    - type: file
      level: debug
      filename: "20060102_debug.log"
      maxSize: 500
      maxBackups: 3
      maxAge: 28
      compress: true
    - type: file
      level: info
      filename: "20060102_info.log"
      maxSize: 500
      maxBackups: 3
      maxAge: 28
      compress: true
    - type: file
      level: warn
      filename: "20060102_warn.log"
      maxSize: 500
      maxBackups: 3
      maxAge: 28
      compress: true
    - type: file
      level: error
      filename: "20060102_error.log"
      maxSize: 500
      maxBackups: 3
      maxAge: 28
      compress: true
    - type: console
  
geth:
  wsAddress: "wss://linea-sepolia.g.alchemy.com/v2/_6dn2JqC0JV9irSos3S9FnkpUafPw6cX"
  address: "https://linea-sepolia.g.alchemy.com/v2/_6dn2JqC0JV9irSos3S9FnkpUafPw6cX"
  donationContract:
    address: "0x6Cf23549b2678027E4A1dDdC34c59c6255d05D13"
    abiPath: "abi/donation.abi"
  nftContract:
    address: "0x0A7Ceb2B9707123ceD34B0f6e444Cc5562bEA3DD"
    abiPath: "abi/nft.abi"
  nft:
    privateKey: "4d793e28b59cae1f0680ebeda1fc70f8019dbd19041c725c02be75f6261962d9"
    chainId: 59141

jwt:
  secretKey: "1234567890"
  whiteList: 
    - "auth/nonce"
    - "auth/login"
