db:
  host: localhost
  port: 3307
  user: root
  password: 123456
  dbname: campaign
  sslmode: disable

redis:
  address: localhost:6379
  password: ""
  db: 0

logging:
  level: info
  format: text
  outputs:
    - type: file
      level: debug
      filename: "20060102_debug.log"
      maxSize: 500
      maxBackups: 3
      maxAge: 28
      compress: true
    - type: file
      level: info
      filename: "20060102_info.log"
      maxSize: 500
      maxBackups: 3
      maxAge: 28
      compress: true
    - type: file
      level: warn
      filename: "20060102_warn.log"
      maxSize: 500
      maxBackups: 3
      maxAge: 28
      compress: true
    - type: file
      level: error
      filename: "20060102_error.log"
      maxSize: 500
      maxBackups: 3
      maxAge: 28
      compress: true
    - type: console
  
geth:
  wsAddress: "wss://eth-sepolia.g.alchemy.com/v2/_6dn2JqC0JV9irSos3S9FnkpUafPw6cX"
  address: "https://eth-sepolia.g.alchemy.com/v2/_6dn2JqC0JV9irSos3S9FnkpUafPw6cX"
  donationContract:
    address: "0x7cd3A9c4A78345450aE7e6FC0c467322109e7661"
    abiPath: "abi/donation.abi"
  nftContract:
    address: "0x5102579fdA461CAEf1cf4F4aa8C4fFb4639e34fC"
    abiPath: "abi/nft.abi"
  nft:
    privateKey: "4d793e28b59cae1f0680ebeda1fc70f8019dbd19041c725c02be75f6261962d9"
    chainId: 11155111

