db:
  host: localhost
  port: 3307
  user: root
  password: 123456
  dbname: campaign
  sslmode: disable

redis:
  address: localhost:6379
  password: ""
  db: 0

logging:
  level: info
  format: text
  outputs:
    - type: file
      level: debug
      filename: "20060102_debug.log"
      maxSize: 500
      maxBackups: 3
      maxAge: 28
      compress: true
    - type: file
      level: info
      filename: "20060102_info.log"
      maxSize: 500
      maxBackups: 3
      maxAge: 28
      compress: true
    - type: file
      level: warn
      filename: "20060102_warn.log"
      maxSize: 500
      maxBackups: 3
      maxAge: 28
      compress: true
    - type: file
      level: error
      filename: "20060102_error.log"
      maxSize: 500
      maxBackups: 3
      maxAge: 28
      compress: true
    - type: console
  
geth:
  deployNetwork: "l2-zk"  # 可选值：l1, l2-zk
  confimationMode: "hard" # 可选值：hard，soft
  l1VerifierContracts:
    linea: "0xA4d0aD7cEE00F2e0eFf5eC3a7B3A1967F815C9e6"  # Linea在L1的验证合约地址
  wsAddressEth: "wss://eth-sepolia.g.alchemy.com/v2/_6dn2JqC0JV9irSos3S9FnkpUafPw6cX"
  addressEth: "https://eth-sepolia.g.alchemy.com/v2/_6dn2JqC0JV9irSos3S9FnkpUafPw6cX"
  wsAddressLinea: ""
  addressLinea: ""
  donationContract:
    address: "0x4943FBb818f92cCb56C6bb9CF115d5248A1F0Ea7"
    abiPath: "abi/donation.abi"
  nftContract:
    address: "0x58e293dBb1407424D3E0E365e381B98e7196Ea6A"
    abiPath: "abi/nft.abi"
  nft:
    privateKey: "4d793e28b59cae1f0680ebeda1fc70f8019dbd19041c725c02be75f6261962d9"
    chainId: 11155111

jwt:
  secretKey: "1234567890"
  whiteList:

service:
  userAuth: "http://localhost:10000/user"

